### ISSUE TITLE
Not python 2 compatible

### ISSUE THREAD

**Issue by dgiridharan** [Akhail/Tebless#1]
I'm not sure if this is supposed to be python 2 compatible but this is released in the pip2.

However - when I try to import this and use this for python2 there are my incompatibles. So far this is what I've seen:

1) No Print function:
   - File: tebless/devs/__init__.py
   - Possible fix: import from __future__ import print_function
2) Literal String Interpolation are used all over the place. 

There might be several others. If this is not compatible with python2, then I'm surprised that this is in pip2. Please I ignore this if this is only compatible with python 3.

**Comment by Akhail** [comment]
Hi @dgiridharan.
Yes, this packages is only available for python 3 version.

**Comment by dgiridharan** [comment]
Should this be taken down from pip2? That way it's not available for python2.
